/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/platform/platform';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from 'ionic-angular/components/content/content';
import * as import14 from 'ionic-angular/components/refresher/refresher';
import * as import15 from 'ionic-angular/components/refresher/refresher-content';
import * as import16 from 'ionic-angular/components/fab/fab';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/icon/icon';
import * as import19 from '@angular/common/src/directives/ng_for';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from 'ionic-angular/util/keyboard';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from 'ionic-angular/gestures/gesture-controller';
import * as import29 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import31 from '@angular/core/src/linker/template_ref';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '@angular/core/src/security';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Platform),this.parentInjector.get(import10.Http));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import12.ComponentFactory<import3.HomePage> = new import12.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import13.Content;
  _text_1:any;
  _el_2:any;
  _Refresher_2_3:import14.Refresher;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _RefresherContent_4_4:import15.RefresherContent;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _FabContainer_8_4:import16.FabContainer;
  _query_FabButton_8_0:import17.QueryList<any>;
  _query_FabList_8_1:import17.QueryList<any>;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _FabButton_10_4:import16.FabButton;
  _el_11:any;
  _Icon_11_3:import18.Icon;
  _text_12:any;
  _el_13:any;
  _FabList_13_3:import16.FabList;
  _query_FabButton_13_0:import17.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _FabButton_15_4:import16.FabButton;
  _el_16:any;
  _Icon_16_3:import18.Icon;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _FabButton_18_4:import16.FabButton;
  _el_19:any;
  _Icon_19_3:import18.Icon;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _FabButton_21_4:import16.FabButton;
  _el_22:any;
  _Icon_22_3:import18.Icon;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _FabButton_24_4:import16.FabButton;
  _el_25:any;
  _Icon_25_3:import18.Icon;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _TemplateRef_34_5:any;
  _NgFor_34_6:import19.NgFor;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','home');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import13.Content(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_2_3 = new import14.Refresher(this._Content_0_4,this.parentInjector.get(import25.NgZone),this.parentInjector.get(import28.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_4,'pullingIcon','arrow-dropdown');
    this.renderer.setElementAttribute(this._el_4,'pullingText','Pull to refresh');
    this.renderer.setElementAttribute(this._el_4,'refreshingSpinner','circles');
    this.renderer.setElementAttribute(this._el_4,'refreshingText','Refreshing...');
    this.renderer.setElementAttribute(this._el_4,'refreshingicon','refresher-pulling-icon');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import29.viewFactory_RefresherContent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._RefresherContent_4_4 = new import15.RefresherContent(this._Refresher_2_3,this.parentInjector.get(import21.Config));
    this._appEl_4.initComponent(this._RefresherContent_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_4.create(this._RefresherContent_4_4,[],(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_8,'middle','');
    this.renderer.setElementAttribute(this._el_8,'right','');
    this._appEl_8 = new import2.AppElement(8,0,this,this._el_8);
    var compView_8:any = import30.viewFactory_FabContainer0(this.viewUtils,this.injector(8),this._appEl_8);
    this._FabContainer_8_4 = new import16.FabContainer(new import22.ElementRef(this._el_8));
    this._query_FabButton_8_0 = new import17.QueryList<any>();
    this._query_FabList_8_1 = new import17.QueryList<any>();
    this._appEl_8.initComponent(this._FabContainer_8_4,[],compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'color','danger');
    this.renderer.setElementAttribute(this._el_10,'ion-fab','');
    this._appEl_10 = new import2.AppElement(10,8,this,this._el_10);
    var compView_10:any = import30.viewFactory_FabButton0(this.viewUtils,this.injector(10),this._appEl_10);
    this._FabButton_10_4 = new import16.FabButton(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._FabButton_10_4,[],compView_10);
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','add');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import18.Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_11),this.renderer);
    compView_10.create(this._FabButton_10_4,[[].concat([this._el_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-fab-list',(null as any));
    this.renderer.setElementAttribute(this._el_13,'side','top');
    this._FabList_13_3 = new import16.FabList();
    this._query_FabButton_13_0 = new import17.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-fab','');
    this._appEl_15 = new import2.AppElement(15,13,this,this._el_15);
    var compView_15:any = import30.viewFactory_FabButton0(this.viewUtils,this.injector(15),this._appEl_15);
    this._FabButton_15_4 = new import16.FabButton(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._FabButton_15_4,[],compView_15);
    this._el_16 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_16,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_16,'role','img');
    this._Icon_16_3 = new import18.Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_16),this.renderer);
    compView_15.create(this._FabButton_15_4,[[].concat([this._el_16])],(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'ion-fab','');
    this._appEl_18 = new import2.AppElement(18,13,this,this._el_18);
    var compView_18:any = import30.viewFactory_FabButton0(this.viewUtils,this.injector(18),this._appEl_18);
    this._FabButton_18_4 = new import16.FabButton(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_18),this.renderer);
    this._appEl_18.initComponent(this._FabButton_18_4,[],compView_18);
    this._el_19 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_19,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_19,'role','img');
    this._Icon_19_3 = new import18.Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_19),this.renderer);
    compView_18.create(this._FabButton_18_4,[[].concat([this._el_19])],(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'ion-fab','');
    this._appEl_21 = new import2.AppElement(21,13,this,this._el_21);
    var compView_21:any = import30.viewFactory_FabButton0(this.viewUtils,this.injector(21),this._appEl_21);
    this._FabButton_21_4 = new import16.FabButton(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_21),this.renderer);
    this._appEl_21.initComponent(this._FabButton_21_4,[],compView_21);
    this._el_22 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_22,'name','logo-vimeo');
    this.renderer.setElementAttribute(this._el_22,'role','img');
    this._Icon_22_3 = new import18.Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_22),this.renderer);
    compView_21.create(this._FabButton_21_4,[[].concat([this._el_22])],(null as any));
    this._text_23 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'ion-fab','');
    this._appEl_24 = new import2.AppElement(24,13,this,this._el_24);
    var compView_24:any = import30.viewFactory_FabButton0(this.viewUtils,this.injector(24),this._appEl_24);
    this._FabButton_24_4 = new import16.FabButton(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_24),this.renderer);
    this._appEl_24.initComponent(this._FabButton_24_4,[],compView_24);
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'name','logo-googleplus');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import18.Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_25),this.renderer);
    compView_24.create(this._FabButton_24_4,[[].concat([this._el_25])],(null as any));
    this._text_26 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n',(null as any));
    this._query_FabButton_8_0.reset([
      this._FabButton_10_4,
      this._FabButton_15_4,
      this._FabButton_18_4,
      this._FabButton_21_4,
      this._FabButton_24_4
    ]
    );
    this._FabContainer_8_4._mainButton = this._query_FabButton_8_0.first;
      compView_8.create(this._FabContainer_8_4,[[].concat([
        this._text_9,
        this._el_10,
        this._text_12,
        this._el_13,
        this._text_27
      ]
    )],(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_29,'href','http://line.me/ti/p/~prettymcthailand');
    this._el_30 = this.renderer.createElement(this._el_29,'img',(null as any));
    this.renderer.setElementAttribute(this._el_30,'src','assets/images/coverhead.png');
    this.renderer.setElementAttribute(this._el_30,'width','100%');
    this._text_31 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','jobhomehead');
    this._text_33 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_32,(null as any));
    this._appEl_34 = new import2.AppElement(34,32,this,this._anchor_34);
    this._TemplateRef_34_5 = new import31.TemplateRef_(this._appEl_34,viewFactory_HomePage1);
    this._NgFor_34_6 = new import19.NgFor(this._appEl_34.vcRef,this._TemplateRef_34_5,this.parentInjector.get(import32.IterableDiffers),this.ref);
    this._text_35 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_32,'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','toAll');
    this._text_37 = this.renderer.createText(this._el_36,'ดูทั้งหมด >>>',(null as any));
    this._text_38 = this.renderer.createText(this._el_32,'\n\n  ',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_40,'src','assets/images/button-urgent.png');
    this._text_41 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [].concat([this._el_8]),
      [].concat([
        this._text_1,
        this._text_7,
        this._text_28,
        this._el_29,
        this._text_31,
        this._el_32,
        this._text_39,
        this._el_40,
        this._text_41
      ]
      ),
      [].concat([this._el_2])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'ionRefresh',this.eventHandler(this._handle_ionRefresh_2_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._Refresher_2_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_2_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_36,'click',this.eventHandler(this._handle_click_36_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_40,'click',this.eventHandler(this._handle_click_40_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.RefresherContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RefresherContent_4_4; }
    if (((token === import14.Refresher) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Refresher_2_3; }
    if (((token === import18.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3; }
    if (((token === import16.FabButton) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._FabButton_10_4; }
    if (((token === import18.Icon) && (16 === requestNodeIndex))) { return this._Icon_16_3; }
    if (((token === import16.FabButton) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._FabButton_15_4; }
    if (((token === import18.Icon) && (19 === requestNodeIndex))) { return this._Icon_19_3; }
    if (((token === import16.FabButton) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._FabButton_18_4; }
    if (((token === import18.Icon) && (22 === requestNodeIndex))) { return this._Icon_22_3; }
    if (((token === import16.FabButton) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._FabButton_21_4; }
    if (((token === import18.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3; }
    if (((token === import16.FabButton) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._FabButton_24_4; }
    if (((token === import16.FabList) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._FabList_13_3; }
    if (((token === import16.FabContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._FabContainer_8_4; }
    if (((token === import31.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import19.NgFor) && (34 === requestNodeIndex))) { return this._NgFor_34_6; }
    if (((token === import13.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_2_3.ngOnInit(); }
    const currVal_4:any = 'arrow-dropdown';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RefresherContent_4_4.pullingIcon = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'Pull to refresh';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RefresherContent_4_4.pullingText = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = 'circles';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._RefresherContent_4_4.refreshingSpinner = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = 'Refreshing...';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RefresherContent_4_4.refreshingText = currVal_7;
      this._expr_7 = currVal_7;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_4_4.ngOnInit(); }
    changed = false;
    const currVal_9:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._FabButton_10_4.color = currVal_9;
      changed = true;
      this._expr_9 = currVal_9;
    }
    if (changed) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_10:any = 'add';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Icon_11_3.name = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = 'logo-facebook';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Icon_16_3.name = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = 'logo-twitter';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Icon_19_3.name = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = 'logo-vimeo';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._Icon_22_3.name = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = 'logo-googleplus';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Icon_25_3.name = currVal_19;
      this._expr_19 = currVal_19;
    }
    changes = (null as any);
    const currVal_21:any = this.context.items;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgFor_34_6.ngForOf = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._NgFor_34_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_34_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_FabButton_13_0.dirty) {
        this._query_FabButton_13_0.reset([
          this._FabButton_15_4,
          this._FabButton_18_4,
          this._FabButton_21_4,
          this._FabButton_24_4
        ]
        );
        this._FabList_13_3._setbuttons = this._query_FabButton_13_0;
        this._query_FabButton_13_0.notifyOnChanges();
      }
      if (this._query_FabList_8_1.dirty) {
        this._query_FabList_8_1.reset([this._FabList_13_3]);
        this._FabContainer_8_4._fabLists = this._query_FabList_8_1;
        this._query_FabList_8_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._FabContainer_8_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = (this._Refresher_2_3.state !== 'inactive');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'refresher-active',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Refresher_2_3._top;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementStyle(this._el_2,'top',((this.viewUtils.sanitizer.sanitize(import33.SecurityContext.STYLE,currVal_3) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import33.SecurityContext.STYLE,currVal_3).toString()));
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._RefresherContent_4_4.r.state;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_4,'state',((currVal_8 == (null as any))? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._Icon_11_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._FabList_13_3._visible;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_13,'fab-list-active',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._Icon_16_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_16,'hide',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_16:any = this._Icon_19_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_19,'hide',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = this._Icon_22_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_22,'hide',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_20:any = this._Icon_25_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Refresher_2_3.ngOnDestroy();
    this._Icon_11_3.ngOnDestroy();
    this._Icon_16_3.ngOnDestroy();
    this._Icon_19_3.ngOnDestroy();
    this._Icon_22_3.ngOnDestroy();
    this._Icon_25_3.ngOnDestroy();
    this._FabContainer_8_4.ngOnDestroy();
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_ionRefresh_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToJoball()) !== false);
    return (true && pd_0);
  }
  private _handle_click_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.launch()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_1,'src','assets/images/new.gif');
    this._text_2 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(2,' ',this.context.$implicit.j_type,' ',this.context.$implicit.j_title,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_2,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToJobdetail(this.parent.context.$events,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}