/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './joball';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/http/src/http';
import * as import11 from 'ionic-angular/platform/platform';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/components/refresher/refresher';
import * as import16 from 'ionic-angular/components/refresher/refresher-content';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from 'ionic-angular/util/keyboard';
import * as import23 from '@angular/core/src/zone/ng_zone';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/tabs/tabs';
import * as import26 from 'ionic-angular/gestures/gesture-controller';
import * as import27 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from '@angular/core/src/security';
import * as import31 from 'ionic-angular/components/icon/icon';
import * as import32 from '@angular/common/src/directives/ng_switch';
var renderType_JobAllPage_Host:import0.RenderComponentType = (null as any);
class _View_JobAllPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _JobAllPage_0_4:import3.JobAllPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage_Host0,renderType_JobAllPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-joball',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_JobAllPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._JobAllPage_0_4 = new import3.JobAllPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.Http),this.parentInjector.get(import11.Platform));
    this._appEl_0.initComponent(this._JobAllPage_0_4,[],compView_0);
    compView_0.create(this._JobAllPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.JobAllPage) && (0 === requestNodeIndex))) { return this._JobAllPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_JobAllPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_JobAllPage_Host === (null as any))) { (renderType_JobAllPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_JobAllPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const JobAllPageNgFactory:import13.ComponentFactory<import3.JobAllPage> = new import13.ComponentFactory<import3.JobAllPage>('page-joball',viewFactory_JobAllPage_Host0,import3.JobAllPage);
const styles_JobAllPage:any[] = [];
var renderType_JobAllPage:import0.RenderComponentType = (null as any);
class _View_JobAllPage0 extends import1.AppView<import3.JobAllPage> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Content_0_4:import14.Content;
  _text_1:any;
  _el_2:any;
  _Refresher_2_3:import15.Refresher;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _RefresherContent_4_4:import16.RefresherContent;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _TemplateRef_12_5:any;
  _NgFor_12_6:import17.NgFor;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import17.NgFor;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage0,renderType_JobAllPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','job-all');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_Content0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Content_0_4 = new import14.Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import22.Keyboard),this.parentInjector.get(import23.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import25.Tabs,(null as any)));
    this._appEl_0.initComponent(this._Content_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_2_3 = new import15.Refresher(this._Content_0_4,this.parentInjector.get(import23.NgZone),this.parentInjector.get(import26.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_4,'pullingIcon','arrow-dropdown');
    this.renderer.setElementAttribute(this._el_4,'pullingText','Pull to refresh');
    this.renderer.setElementAttribute(this._el_4,'refreshingSpinner','circles');
    this.renderer.setElementAttribute(this._el_4,'refreshingText','Refreshing...');
    this.renderer.setElementAttribute(this._el_4,'refreshingicon','refresher-pulling-icon');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import27.viewFactory_RefresherContent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._RefresherContent_4_4 = new import16.RefresherContent(this._Refresher_2_3,this.parentInjector.get(import19.Config));
    this._appEl_4.initComponent(this._RefresherContent_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_4.create(this._RefresherContent_4_4,[],(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','joballhead');
    this._text_9 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'img',(null as any));
    this.renderer.setElementAttribute(this._el_10,'src','assets/images/bar-today.png');
    this._text_11 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_8,(null as any));
    this._appEl_12 = new import2.AppElement(12,8,this,this._anchor_12);
    this._TemplateRef_12_5 = new import28.TemplateRef_(this._appEl_12,viewFactory_JobAllPage1);
    this._NgFor_12_6 = new import17.NgFor(this._appEl_12.vcRef,this._TemplateRef_12_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_13 = this.renderer.createText(this._el_8,'\n  ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','joballhead2');
    this._text_16 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'img',(null as any));
    this.renderer.setElementAttribute(this._el_17,'src','assets/images/bar-job.png');
    this._text_18 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_19 = new import2.AppElement(19,15,this,this._anchor_19);
    this._TemplateRef_19_5 = new import28.TemplateRef_(this._appEl_19,viewFactory_JobAllPage2);
    this._NgFor_19_6 = new import17.NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_20 = this.renderer.createText(this._el_15,'\n  ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Content_0_4,[
      [],
      [].concat([
        this._text_1,
        this._text_7,
        this._el_8,
        this._text_14,
        this._el_15,
        this._text_21
      ]
      ),
      [].concat([this._el_2])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'ionRefresh',this.eventHandler(this._handle_ionRefresh_2_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._Refresher_2_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_2_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.RefresherContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._RefresherContent_4_4; }
    if (((token === import15.Refresher) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Refresher_2_3; }
    if (((token === import28.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import17.NgFor) && (12 === requestNodeIndex))) { return this._NgFor_12_6; }
    if (((token === import28.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import17.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6; }
    if (((token === import14.Content) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Content_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_0_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_2_3.ngOnInit(); }
    const currVal_4:any = 'arrow-dropdown';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RefresherContent_4_4.pullingIcon = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'Pull to refresh';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RefresherContent_4_4.pullingText = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = 'circles';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._RefresherContent_4_4.refreshingSpinner = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = 'Refreshing...';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RefresherContent_4_4.refreshingText = currVal_7;
      this._expr_7 = currVal_7;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_4_4.ngOnInit(); }
    changes = (null as any);
    const currVal_9:any = this.context.itemstoday;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgFor_12_6.ngForOf = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgFor_12_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_12_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_10:any = this.context.items;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_19_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_19_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_19_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Content_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = (this._Refresher_2_3.state !== 'inactive');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'refresher-active',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Refresher_2_3._top;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementStyle(this._el_2,'top',((this.viewUtils.sanitizer.sanitize(import30.SecurityContext.STYLE,currVal_3) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import30.SecurityContext.STYLE,currVal_3).toString()));
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._RefresherContent_4_4.r.state;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_4,'state',((currVal_8 == (null as any))? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Refresher_2_3.ngOnDestroy();
    this._Content_0_4.ngOnDestroy();
  }
  private _handle_ionRefresh_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_JobAllPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.JobAllPage> {
  if ((renderType_JobAllPage === (null as any))) { (renderType_JobAllPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_JobAllPage,{})); }
  return new _View_JobAllPage0(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage1,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','jobhome');
    this._el_1 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_1,'src','assets/images/new.gif');
    this._text_2 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(2,' ',this.context.$implicit.j_type,' ',this.context.$implicit.j_title,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_2,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToJobdetail(this.parent.context.$events,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_JobAllPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage1(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _Icon_1_3:import31.Icon;
  _text_2:any;
  _el_3:any;
  _NgSwitch_3_3:import32.NgSwitch;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgSwitchCase_5_6:import32.NgSwitchCase;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _TemplateRef_7_5:any;
  _NgSwitchCase_7_6:import32.NgSwitchCase;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgSwitchCase_9_6:import32.NgSwitchCase;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgSwitchCase_11_6:import32.NgSwitchCase;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgSwitchCase_13_6:import32.NgSwitchCase;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage2,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','jobhome');
    this._el_1 = this.renderer.createElement(this._el_0,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_1,'name','arrow-dropright');
    this.renderer.setElementAttribute(this._el_1,'role','img');
    this._Icon_1_3 = new import31.Icon(this.parent.parentInjector.get(import19.Config),new import20.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'span',(null as any));
    this._NgSwitch_3_3 = new import32.NgSwitch();
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import28.TemplateRef_(this._appEl_5,viewFactory_JobAllPage3);
    this._NgSwitchCase_5_6 = new import32.NgSwitchCase(this._appEl_5.vcRef,this._TemplateRef_5_5,this._NgSwitch_3_3);
    this._text_6 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_7 = new import2.AppElement(7,3,this,this._anchor_7);
    this._TemplateRef_7_5 = new import28.TemplateRef_(this._appEl_7,viewFactory_JobAllPage4);
    this._NgSwitchCase_7_6 = new import32.NgSwitchCase(this._appEl_7.vcRef,this._TemplateRef_7_5,this._NgSwitch_3_3);
    this._text_8 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_9 = new import2.AppElement(9,3,this,this._anchor_9);
    this._TemplateRef_9_5 = new import28.TemplateRef_(this._appEl_9,viewFactory_JobAllPage5);
    this._NgSwitchCase_9_6 = new import32.NgSwitchCase(this._appEl_9.vcRef,this._TemplateRef_9_5,this._NgSwitch_3_3);
    this._text_10 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_11 = new import2.AppElement(11,3,this,this._anchor_11);
    this._TemplateRef_11_5 = new import28.TemplateRef_(this._appEl_11,viewFactory_JobAllPage6);
    this._NgSwitchCase_11_6 = new import32.NgSwitchCase(this._appEl_11.vcRef,this._TemplateRef_11_5,this._NgSwitch_3_3);
    this._text_12 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_13 = new import2.AppElement(13,3,this,this._anchor_13);
    this._TemplateRef_13_5 = new import28.TemplateRef_(this._appEl_13,viewFactory_JobAllPage7);
    this._NgSwitchCase_13_6 = new import32.NgSwitchCase(this._appEl_13.vcRef,this._TemplateRef_13_5,this._NgSwitch_3_3);
    this._text_14 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.Icon) && (1 === requestNodeIndex))) { return this._Icon_1_3; }
    if (((token === import28.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import32.NgSwitchCase) && (5 === requestNodeIndex))) { return this._NgSwitchCase_5_6; }
    if (((token === import28.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import32.NgSwitchCase) && (7 === requestNodeIndex))) { return this._NgSwitchCase_7_6; }
    if (((token === import28.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import32.NgSwitchCase) && (9 === requestNodeIndex))) { return this._NgSwitchCase_9_6; }
    if (((token === import28.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import32.NgSwitchCase) && (11 === requestNodeIndex))) { return this._NgSwitchCase_11_6; }
    if (((token === import28.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import32.NgSwitchCase) && (13 === requestNodeIndex))) { return this._NgSwitchCase_13_6; }
    if (((token === import32.NgSwitch) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgSwitch_3_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'arrow-dropright';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_1_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this.context.$implicit.j_type;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgSwitch_3_3.ngSwitch = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = 'pretty';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgSwitchCase_5_6.ngSwitchCase = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'mc';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgSwitchCase_7_6.ngSwitchCase = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = 'smartboy';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgSwitchCase_9_6.ngSwitchCase = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = 'model';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgSwitchCase_11_6.ngSwitchCase = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = 'actor';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgSwitchCase_13_6.ngSwitchCase = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_1_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_1,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_9:any = import4.interpolate(1,' ',this.context.$implicit.j_title,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_15,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_1_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToJobdetail(this.parent.context.$events,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_JobAllPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage2(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage3,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'PT',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobAllPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage3(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage4,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'MC',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobAllPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage4(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage5,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'SB',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobAllPage5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage5(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage6,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'MD',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobAllPage6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage6(viewUtils,parentInjector,declarationEl);
}
class _View_JobAllPage7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobAllPage7,renderType_JobAllPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'AC',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobAllPage7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobAllPage7(viewUtils,parentInjector,declarationEl);
}